name: mu_state
description: Minimal Cubit-inspired state management using Flutter's built-in primitives. No external dependencies.
version: 2.0.0+4
homepage: https://github.com/erf/mu_state

topics:
  - state-management
  - cubit
  - state
  - valuenotifier
  - minimal

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
